[package]
name = "emerald_mobile_wallet"
version = "0.1.0"
authors = ["Mark Mathis <markmathis@gmail.com>"]

[lib]
name = "emerald_mobile_wallet"
crate-type = ["staticlib", "cdylib"]

[dependencies]
libc = "0.2"
jni = { version = "0.5.1", optional = true, default-features = false }

[features]
default = ["jni"]
